#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

usage() {
  cat >&2 <<'USAGE'
usage: scripts/generate-artifacts.sh <planning-run-id>

Creates missing planned artifact files conservatively and updates the planning
manifest. Existing tracked artifact files are not overwritten.
USAGE
}

if [[ $# -ne 1 ]]; then
  usage
  exit 2
fi

RUN_ID="$1"

case "$RUN_ID" in
  */*|*..*|"")
    echo "invalid run id: $RUN_ID" >&2
    exit 2
    ;;
esac

MANIFEST="agentic/runs/$RUN_ID/manifest.yaml"

if [[ ! -f "$MANIFEST" ]]; then
  echo "planning manifest not found: $MANIFEST" >&2
  exit 1
fi

RUN_ID="$RUN_ID" MANIFEST="$MANIFEST" ruby <<'RUBY'
require "digest"
require "fileutils"
require "time"
require "yaml"

run_id = ENV.fetch("RUN_ID")
manifest_path = ENV.fetch("MANIFEST")
manifest = YAML.load_file(manifest_path)
run = manifest["run"] || {}
now = Time.now.utc.iso8601

unless run["id"].to_s == run_id
  warn "run.id mismatch: expected #{run_id}, got #{run["id"] || "(empty)"}"
  exit 1
end

private_patterns = [
  Regexp.new("private product " + "name", Regexp::IGNORECASE),
  Regexp.new("private strategy " + "file", Regexp::IGNORECASE),
  Regexp.new("customer " + "name", Regexp::IGNORECASE),
  Regexp.new("ownership[_-]" + "token", Regexp::IGNORECASE),
  Regexp.new("vu" + "lcan", Regexp::IGNORECASE),
  Regexp.new("secure " + "harness", Regexp::IGNORECASE),
  Regexp.new("private agent runtime " + "gateway", Regexp::IGNORECASE),
  Regexp.new("origin-" + "strategy", Regexp::IGNORECASE)
]

def public_safe_path?(path)
  return false if path.to_s.empty?
  return false if path.start_with?("/")
  return false if path.split("/").include?("..")
  true
end

def draft_content_for(path, run_id, goal, now)
  if File.extname(path) =~ /\.ya?ml\z/i
    {
      "schema_version" => 1,
      "generated_by" => "scripts/generate-artifacts.sh",
      "run_id" => run_id,
      "status" => "drafted",
      "generated_at" => now,
      "goal" => goal.to_s.empty? ? "Public-safe delivery goal" : goal,
      "notes" => [
        "Draft scaffold only.",
        "Review and explicit artifact approval are required before implementation."
      ],
      "validation" => {
        "command" => "scripts/validate-artifact-templates.sh #{run_id} --artifact #{path}"
      },
      "rollback" => {
        "notes" => "Remove or revise this draft and rerun artifact generation."
      },
      "review_expectations" => [
        "AIT review evidence remains ignored.",
        "Approval must be an explicit manifest status transition."
      ]
    }.to_yaml
  else
    <<~TEXT
      # Draft Artifact

      ## Purpose

      Generated by `scripts/generate-artifacts.sh`.

      Run: #{run_id}
      Status: drafted
      Generated at: #{now}

      ## Scope

      Produce a public-safe draft artifact for the current planning run.

      Goal:

      #{goal.to_s.empty? ? "Public-safe delivery goal." : goal}

      ## Acceptance Criteria

      - The artifact remains public-safe.
      - The artifact can be reviewed by AIT and Claude Code.
      - The artifact is not used for implementation until explicitly approved.

      ## Validation

      ```bash
      scripts/validate-artifact-templates.sh #{run_id} --artifact #{path}
      ```

      ## Rollback

      Remove or revise this draft and rerun artifact generation.

      ## Review Expectations

      This draft is not approved. It must pass review and receive an explicit
      `approved` artifact status before it can drive implementation.
    TEXT
  end
end

artifacts = Array(manifest["artifacts"])
errors = []
generated = []

artifacts.each do |artifact|
  next unless artifact.is_a?(Hash)

  path = artifact["path"].to_s
  unless public_safe_path?(path)
    errors << "invalid artifact path: #{path}"
    next
  end

  status = artifact["status"].to_s
  next if %w[approved rejected deferred].include?(status)
  next unless %w[planned drafted changes_requested].include?(status)

  FileUtils.mkdir_p(File.dirname(path))
  created = false

  unless File.file?(path)
    content = draft_content_for(path, run_id, run["goal"], now)
    matching_private_pattern = private_patterns.find { |pattern| content.match?(pattern) }
    if matching_private_pattern
      errors << "generated text failed public-safety pattern for #{path}: #{matching_private_pattern.inspect}"
      next
    end

    File.write(path, content)
    created = true
  end

  content = File.file?(path) ? File.read(path) : ""
  matching_private_pattern = private_patterns.find { |pattern| content.match?(pattern) }
  if matching_private_pattern
    errors << "artifact text failed public-safety pattern for #{path}: #{matching_private_pattern.inspect}"
    next
  end

  old_status = status.empty? ? "planned" : status
  artifact["status"] = "drafted" if %w[planned changes_requested].include?(old_status)
  artifact["updated_at"] = now
  artifact["updated_by"] = "generate-artifacts"
  artifact["generation"] = {
    "generated_by" => "scripts/generate-artifacts.sh",
    "generated_at" => now,
    "created_file" => created,
    "content_sha256" => Digest::SHA256.hexdigest(content)
  }
  artifact["status_history"] = Array(artifact["status_history"])

  if old_status != artifact["status"]
    artifact["status_history"] << {
      "from_status" => old_status,
      "to_status" => artifact["status"],
      "at" => now,
      "actor" => "generate-artifacts",
      "reason" => "Draft artifact generated or refreshed from public-safe run context"
    }
  end

  generated << {
    "path" => path,
    "status" => artifact["status"],
    "created_file" => created,
    "content_sha256" => artifact["generation"]["content_sha256"]
  }
end

unless errors.empty?
  errors.each { |error| warn error }
  exit 1
end

manifest["generated_artifacts"] = Array(manifest["generated_artifacts"]) + generated
manifest["run"] ||= {}
manifest["run"]["state"] = "draft_artifacts_ready"
manifest["run"]["updated_at"] = now
manifest["run"]["state_history"] = Array(manifest["run"]["state_history"])
manifest["run"]["state_history"] << {
  "state" => "draft_artifacts_ready",
  "at" => now
}

File.write(manifest_path, manifest.to_yaml)

puts "generated artifacts: #{generated.length}"
generated.each { |item| puts "- #{item["path"]} status=#{item["status"]} created=#{item["created_file"]}" }
RUBY

scripts/validate-artifact-templates.sh "$RUN_ID" >/dev/null
